language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
before_deploy:
  - "sed -i '/build.html/d' .gitignore"
  - "sed -i '/images/images.json/d' .gitignore"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: master